---

# This task is designed to be called via `ansible.builtin.include_role`.
#
# Parent task tags wouldn't be inherited here, so we apply an 'always' to
# ensure that jobs including this task will run it, not just include it.
#
- name: Ensure i386 is a valid architecture
  tags:
    - always
  block:
    - name: Get current architectures
      ansible.builtin.command:
        cmd: dpkg --print-foreign-architectures
      changed_when: false  # idempotent
      register: dpkg_current_arch

    - name: Add i386 as a valid architecture
      ansible.builtin.command:
        cmd: dpkg --add-architecture i386
      register: dpkg_added_arch
      changed_when: "dpkg_added_arch.rc == 0"
      when: "'i386' not in dpkg_current_arch.stdout_lines"
