---

- name: Gather installed package lists.
  vars:
    apt_action_type: 'installed'
  ansible.builtin.include_role:
    name: apt
  tags:
    - flatpak


- name: Install Flatpak
  vars:
    dependencies:
      - flatpak
      - gnome-software-plugin-flatpak  # Assumes GNOME
  tags:
    - flatpak
  ansible.builtin.apt:
    update_cache: true
    name:
      - "{{ item }}"
  with_items: "{{ dependencies | difference(apt_installed_packages) }}"


- name: Refresh installed package lists.
  vars:
    apt_action_type: 'installed'
  ansible.builtin.include_role:
    name: apt
  tags:
    - flatpak


- name: Define required flatpak remotes
  when: "'flatpak' in apt_installed_packages"
  tags:
    - flatpak
  community.general.flatpak_remote:
    name: "{{ item.remote.name }}"
    state: present
    flatpakrepo_url: "{{ item.remote.url }}"
  with_items: "{{ flatpak.default_remotes }}"


- name: Check current Flatpak packages
  when: "'flatpak' in apt_installed_packages"
  tags:
    - flatpak
  ansible.builtin.shell:
    cmd: set -o pipefail && flatpak list --columns=application | tail -n +1
    executable: /bin/bash
  changed_when: false  # Legitimately idempotent
  register: flatpak_installed_packages


# TODO - we should be configuring Creality here, as well.
#   ref: https://github.com/CrealityOfficial/CrealityPrint/releases
#
# The 'problem' with Creality is that it isn't hosted on a Flatpak repository,
# so we'd need wget or something to grab the release binary and THEN we can
# install it with `flatpak install $DWN_PATH`
#

# https://docs.ansible.com/ansible/latest/collections/community/general/flatpak_module.html
#
- name: Install managed system Flatpak packages as required
  vars:
    packages: "{{ flatpak.default_packages }}"
  tags:
    - flatpak
  when: "flatpak.default_packages is not subset(flatpak_installed_packages)"
  community.general.flatpak:
    name: "{{ item }}"
    state: present  # We won't assert upgrades.
  with_items: "{{ packages | difference(flatpak_installed_packages) }}"
