# test-container:
#   Intended to provide a 'isolated' and interactive environment for testing
#   Ansible playbooks and associated system configuration.
#
# To build:
#   docker build --file Dockerfile --build-arg INPUT_USERNAME=$USER .
#
# It's recommended to run this image via `docker compose`:
#   docker compose run --remove-orphans --force-recreate -it testing
#
FROM debian:bookworm AS test-container
SHELL ["/bin/bash", "-exo", "pipefail", "-c"]
USER root
ARG INPUT_USERNAME=unset-username
COPY ./bootstrap.sh /opt/bootstrap.sh
# hadolint ignore=DL3008
RUN \
    apt-get update \
    && apt-get dist-upgrade --assume-yes \
    && apt-get install --assume-yes --no-install-recommends \
        vim \
        # `openssl` is required for both password generation, and for the
        # Ansible runtime to resolve URLs, etc., properly.
        #
        openssl \
    && useradd -p "$(openssl passwd -6 'foo')" -ms /bin/bash "${INPUT_USERNAME}" \
    # FIXME: Should implement `bootstrap.sh` functionality here with Docker
    # directives, and/or re-implement it in Python/Ansible.
    #
    && /opt/bootstrap.sh \
    && rm --force --recursive /root/.cache \
    && rm --force /opt/bootstrap.sh \
    && apt-get clean --assume-yes \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /opt
USER ${INPUT_USERNAME}
# We modify the PATH to ensure the .venv generated by the bootstrap command is
# sourced as part of loading into our environment.
#
ENV PATH="/home/${INPUT_USERNAME}/venvs/ansible/bin:${PATH}"
