---
apt:
  keyring: "/etc/apt/keyrings"
  sources: "/etc/apt/sources.list.d"
  managed: "/etc/apt/sources.list.d/debian.list"

su_user: root
su_group: root
docker_group: docker
system_user: darianculver

keys:
  private: true
  public: true

node:
  node_version: 22
  nvm_version: "0.40.3"
  install_path: /tmp/nvm.sh

