---

- name: Gather installed package lists.
  vars:
    apt_action_type: 'installed'
  ansible.builtin.include_role:
    name: apt
  tags:
    - spotify


- name: Setup Spotify
  tags:
    - spotify
  when: "'spotify-client' not in apt_installed_packages"
  block:
    - name: Ensure trusted directory exists
      ansible.builtin.file:
        mode: "0755"
        state: directory
        owner: "{{ su_user }}"
        group: "{{ su_group }}"
        path: "{{ apt.trusted }}"

    - name: Install Spotify keyring
      ansible.builtin.get_url:
        mode: "0644"
        owner: "{{ su_user }}"
        group: "{{ su_group }}"
        # Note: The Public Key identifier is subject to change, and has
        # happened at least twice. So... In cases whereby Spotify installations
        # no longer work, check that the `pubkey_.*` string below matches
        # the remote, here:
        #   https://www.spotify.com/de-en/download/linux/
        #
        url: >-
          https://download.spotify.com/{{ ansible_facts.os_family | lower }}/pubkey_C85668DF69375001.gpg
        dest: "{{ apt.trusted }}/spotify.asc"

    - name: Setup Spotify source
      ansible.builtin.template:
        src: templates/apt-source.j2
        dest: "{{ apt.sources }}/spotify.list"
        owner: "{{ su_user }}"
        group: "{{ su_group }}"
        mode: "0644"

    - name: Install Spotify
      ansible.builtin.apt:
        clean: true
        update_cache: true
        install_recommends: false
        name:
          - spotify-client
