---

- name: Check for installed packages
  ansible.builtin.package_facts:
    manager:
      - apt
  register: packages
  tags:
    - steam


- name: Install Steam packages
  vars:
    steam_packages:
      - mesa-vulkan-drivers
      - libglx-mesa0:i386
      - mesa-vulkan-drivers:i386
      - libgl1-mesa-dri:i386
      - libgl1-mesa-glx:i386
      - steam-installer
  tags:
    - steam
  when: "steam_packages is not subset(ansible_facts['packages'].keys())"
  block:
    - name: Ensure managed apt sources are deployed
      vars:
        apt_action_type: 'sources'
      ansible.builtin.include_role:
        name: apt

    - name: Ensure i386 packages can be installed
      ansible.builtin.include_role:
        name: dpkg

    - name: Install Steam packages
      ansible.builtin.apt:
        update_cache: true
        name:
          - "{{ item }}"
      with_items: "{{ steam_packages | difference(packages['ansible_facts']['packages'].keys()) }}"
