---

- name: Check host_var key declarations
  tags:
    - keys
  when: "keys['public'] or keys['private']"
  block:
    - name: Ensure ssh directory exists
      ansible.builtin.file:
        dest: "/home/{{ system_user }}/.ssh"
        group: "{{ system_user }}"
        owner: "{{ system_user }}"
        mode: "0700"
        state: directory

    - name: Deploy Public
      ansible.builtin.copy:
        src: vault/public
        dest: "/home/{{ system_user }}/.ssh/id_rsa.pub"
        group: "{{ system_user }}"
        owner: "{{ system_user }}"
        mode: "0644"
      when: "keys['public']"

    - name: Deploy Private
      ansible.builtin.copy:
        src: vault/private
        dest: "/home/{{ system_user }}/.ssh/id_rsa"
        group: "{{ system_user }}"
        owner: "{{ system_user }}"
        mode: "0600"
      when: "keys['private']"
