---

# Note: This file contains ansible-lint ignores; this is because this use of
# git is not applicable to Ansible's git module.

- name: Gather installed package lists.
  vars:
    apt_action_type: 'installed'
  ansible.builtin.include_role:
    name: apt
  tags:
    - git


- name: Ensure git is installed
  ansible.builtin.apt:
    update_cache: true
    name:
      - git
  tags:
    - git
  when: "'git' not in apt_installed_packages"


# TODO - add `system_user` validation.
#
- name: Ensure config file is present
  ansible.builtin.file:
    state: touch
    path: "/home/{{ system_user }}/.gitconfig"
    mode: "0644"
    group: "{{ system_user }}"
    owner: "{{ system_user }}"
  tags:
    - git


- name: Configure default commit editor
  become: true
  become_user: "{{ system_user }}"
  tags:
    - git
  block:
    - name: Get current editor  # noqa: command-instead-of-module
      ansible.builtin.command:
        cmd: git config --global core.editor
      changed_when: false  # Command has no affect.
      register: git_editor
      failed_when: git_editor.rc not in (0, 1)

    - name: Set editor to vim  # noqa: command-instead-of-module
      ansible.builtin.command:
        cmd: git config --global core.editor "vim"
      register: git_update_editor
      changed_when: git_update_editor.rc == 0
      when: git_editor.rc == 1 or "vim" not in git_editor.stdout_lines


- name: Check if a signing name is defined.  # noqa: command-instead-of-module
  become: true
  become_user: "{{ system_user }}"
  tags:
    - git
  ansible.builtin.command:
    cmd: git config --global user.name
  register: git_name
  changed_when: false  # Idempotent
  failed_when: git_name.rc not in (0, 1)


- name: Set a signing username, if required.
  become: true
  become_user: "{{ system_user }}"
  tags:
    - git
  when: git_name.rc == 1
  block:
    - name: Prompt user for a signing username.
      ansible.builtin.pause:
        prompt: "What name should be used to sign commits?"
        echo: true
      register: git_new_name

    - name: Set signing username.  # noqa: command-instead-of-module
      ansible.builtin.command:
        cmd: git config --global user.name "{{ git_new_name.user_input }}"
      changed_when: true  # Could probably be improved.


- name: Check if signing email is defined.  # noqa: command-instead-of-module
  become: true
  become_user: "{{ system_user }}"
  tags:
    - git
  ansible.builtin.command:
    cmd: git config --global user.email
  register: git_email
  changed_when: false  # Idempotent
  failed_when: git_email.rc not in (0, 1)


- name: Set a signing email, if required.
  become: true
  become_user: "{{ system_user }}"
  tags:
    - git
  when: git_email.rc == 1
  block:
    - name: Prompt user for a signing email.
      ansible.builtin.pause:
        prompt: "What email should be used to sign commits?"
        echo: true
      register: git_new_email

    - name: Set signing email.  # noqa: command-instead-of-module
      ansible.builtin.command:
        cmd: git config --global user.email "{{ git_new_email.user_input }}"
      changed_when: true  # Could probably be improved.
