---
- name: Provision system
  hosts: localhost
  gather_facts: true
  become: true
  become_user: root
  any_errors_fatal: true
  vars:
    system_user: darianculver  # Change this line as needed.
  debugger: 'on_failed'  # Toggle as needed.

  pre_tasks:

    # Note: Ubuntu is not 'natively' supported - largely CI only.
    - name: Check if 'os_family' is supported
      ansible.builtin.assert:
        that:
          - "{{ ansible_facts.os_family in ('Debian', 'Ubuntu') }}"
        fail_msg: "Error! '{{ ansible_facts.os_family }}' is not supported!"
        success_msg: "'{{ ansible_facts.os_family }}' is supported."
      tags: ['always', 'os_family']

    # FIXME - consider this for managing users on init?
    # https://docs.ansible.com/ansible/latest/collections/ansible \
    # /builtin/user_module.html

    - name: Update apt-cache
      ansible.builtin.apt:
        clean: true
        update_cache: true
      tags: ['always', 'apt', 'cache']

    - name: Upgrade default packages
      ansible.builtin.apt:
        upgrade: "safe"
      tags: ['apt', 'upgrade']

  tasks:

    - name: Install packages from default repositories
      ansible.builtin.apt:
        install_recommends: false
        name:
          - git
          - vim
          - ca-certificates
          - curl
          - dpkg
          - sudo  # Required for 'become' to work.
      tags: ['always', 'apt', 'install']

    - name: Create keyrings directory
      ansible.builtin.file:
        owner: root
        group: root
        mode: "0755"
        path: /etc/apt/keyrings
        state: directory
      tags: ['always', 'apt', 'keyring']

    - name: Install Docker keyring
      ansible.builtin.get_url:
        url: "https://download.docker.com/linux/{{
          ansible_facts.os_family | lower }}/gpg"
        owner: root
        group: root
        mode: "0644"
        dest: /etc/apt/keyrings/docker.asc
      tags: ['keyring', 'docker']

    - name: Setup Docker source
      ansible.builtin.template:
        src: templates/docker-source.j2
        dest: /etc/apt/sources.list.d/docker.list
        owner: root
        group: root
        mode: "0644"
      tags: ['source', 'apt', 'docker']

    - name: Install Docker
      ansible.builtin.apt:
        clean: true
        update_cache: true
        install_recommends: false
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
      tags: ['apt', 'docker']

    - name: Install Spotify keyring
      ansible.builtin.get_url:
        url: "https://download.spotify.com/debian/pubkey_6224F9941A8AA6D1.gpg"
        owner: root
        group: root
        mode: "0644"
        dest: /etc/apt/keyrings/spotify.asc
      tags: ['keyring', 'spotify']

    - name: Setup Spotify source
      ansible.builtin.template:
        src: templates/spotify-source.j2
        dest: /etc/apt/sources.list.d/spotify.list
        owner: root
        group: root
        mode: "0644"
      tags: ['source', 'apt', 'spotify']

    - name: Install Spotify
      ansible.builtin.apt:
        clean: true
        update_cache: true
        install_recommends: false
        name:
          - spotify-client
      tags: ['apt', 'spotify']

    - name: Install Codium keyring
      ansible.builtin.get_url:
        url:
          "https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/\
          raw/master/pub.gpg"
        owner: root
        group: root
        mode: "0644"
        dest: /etc/apt/keyrings/codium.asc
      tags: ['keyring', 'codium']

    - name: Setup Codium source
      ansible.builtin.template:
        src: templates/codium-source.j2
        dest: /etc/apt/sources.list.d/codium.list
        owner: root
        group: root
        mode: "0644"
      tags: ['source', 'apt', 'codium']

    - name: Install Codium
      ansible.builtin.apt:
        clean: true
        update_cache: true
        install_recommends: false
        name:
          - codium
      tags: ['apt', 'codium']

    - name: Ensure Codium config directory tree is present
      ansible.builtin.file:
        state: directory
        owner: "{{ system_user }}"
        group: "{{ system_user }}"
        path: "/home/{{ system_user }}/.config/VSCodium/User"
        recurse: true
      tags: ['codium', 'settings']

    - name: Install Codium settings
      ansible.builtin.copy:
        src: vscode/settings.json
        dest: "/home/{{ system_user }}/.config/VSCodium/User/settings.json"
        owner: "{{ system_user }}"
        group: "{{ system_user }}"
        mode: "0644"
      tags: ['codium', 'settings']

    - name: Install Codium keybindings
      ansible.builtin.copy:
        src: vscode/keybindings.json
        dest: "/home/{{ system_user }}/.config/VSCodium/User/keybindings.json"
        owner: "{{ system_user }}"
        group: "{{ system_user }}"
        mode: "0644"
      tags: ['codium', 'settings']

    - name: Determine installed Codium extensions
      become_user: "{{ system_user }}"
      become: true
      ansible.builtin.command:
        cmd: codium --list-extensions
      register: installed_extensions
      changed_when: installed_extensions.stdout_lines | length > 0
      tags: ['codium', 'extensions']

    - name: Determine Codium extensions to install
      become_user: "{{ system_user }}"
      become: true
      ansible.builtin.command:
        cmd: cat vscode/extensions.txt
      register: extensions_to_install
      changed_when: extensions_to_install.rc == 0
      tags: ['codium', 'extensions']

    - name: Install required Codium extensions
      become_user: "{{ system_user }}"
      become: true
      ansible.builtin.command:
        cmd: codium --install-extension {{ item }}
      register: extension_install_process
      with_items: "{{ extensions_to_install.stdout_lines | difference(installed_extensions.stdout_lines) }}"  # yamllint disable-line rule:line-length
      changed_when: extension_install_process.rc == 0
      tags: ['codium', 'extensions']

    - name: Install nVidia prerequisite drivers
      become: true
      ansible.builtin.apt:
        clean: true
        update_cache: true
        install_recommends: false
        name:
          - linux-headers-amd64
      tags: ['nvidia', 'apt']

    - name: Replace apt sources.list for nVidia drivers
      ansible.builtin.template:
        src: templates/sources.j2
        dest: /etc/apt/sources.list
        owner: root
        group: root
        mode: "0644"
      tags: ['source', 'apt', 'nvidia']

    - name: Install nVidia drivers
      become: true
      ansible.builtin.apt:
        clean: true
        update_cache: true
        install_recommends: true  # Just install defaults - risky install.
        name:
          - nvidia-driver=535.183.01-1~deb12u1  # Would be nice to pin releases.
          - firmware-misc-nonfree=20230210-5
      tags: ['nvidia', 'apt']
