---
- name: Provision system
  hosts: localhost
  gather_facts: true
  become: true
  become_user: root
  any_errors_fatal: true
  vars:  # FIXME; should have a pre_task for user provided values.
    system_user: darianculver  # Change this line as needed.
    git_email: "culver.darian@gmail.com"
    git_author: "Darian Culver"
  debugger: 'on_failed'

  pre_tasks:

    # Note: Ubuntu is not 'natively' supported - largely CI only.
    - name: Check if 'os_family' is supported
      ansible.builtin.assert:
        that:
          - "{{ ansible_facts.os_family in ('Debian', 'Ubuntu') }}"
        fail_msg: "Error! '{{ ansible_facts.os_family }}' is not supported!"
        success_msg: "'{{ ansible_facts.os_family }}' is supported."
      tags: ['always', 'os_family']

    - name: Check system_user exists
      ansible.builtin.command:
        cmd: id {{ system_user }}
      register: user_state
      changed_when: user_state.rc
      failed_when: user_state.rc != 0
      tags: ['always', 'user']

    # FIXME - consider this for managing users on init?
    # https://docs.ansible.com/ansible/latest/collections/ansible \
    # /builtin/user_module.html

    - name: Update apt-cache
      ansible.builtin.apt:
        clean: true
        update_cache: true
      tags: ['always', 'apt', 'cache']

    - name: Upgrade default packages
      ansible.builtin.apt:
        upgrade: "safe"
      tags: ['apt', 'upgrade']

  tasks:
    - name: Install packages from default repositories
      ansible.builtin.apt:
        install_recommends: false
        update_cache: true
        name:
          - git
          - vim
          - ca-certificates
          - curl
          - dpkg
          - sudo  # Required for 'become' to work.
          - jq
          - yq
          - python3-pip
          - keepassxc  # TODO - Need a solution for pull key dbs.
      tags: ['always', 'apt', 'install']

    - name: Check if using gnome
      ansible.builtin.command:
        cmd: apt policy gnome
      register: gnome_status
      changed_when: gnome_status.rc == 0
      tags: ['apt', 'gnome']

    - name: Set up Dashboard favorites
      vars:
        check_string: "Installed: (none)"  # deal w/inline YAML tag (:).
      ansible.builtin.command:
        cmd: >-
          gsettings set org.gnome.shell favorite-apps
          "[
          'org.gnome.Nautilus.desktop',
          'firefox-esr.desktop',
          'spotify.desktop',
          'codium.desktop',
          'steam.desktop',
          'org.gnome.Terminal.desktop',
          'org.keepassxc.KeePassXC.desktop'
          ]"
      register: dashboard_favorites
      changed_when: dashboard_favorites.rc == 0
      when: gnome_status.stdout_lines[1] | trim != check_string
      tags: ['apt', 'gnome']

    - name: Set up git config
      tags: ['git']
      block:  # FIXME; we should use the git module, but this works for now.
        - name: Define username  # noqa: command-instead-of-module
          ansible.builtin.command:
            cmd: git config --global user.name "{{ git_author }}"
          register: git_set_username
          changed_when: git_set_username.rc == 0

        - name: Define email  # noqa: command-instead-of-module
          ansible.builtin.command:
            cmd: git config --global user.email "{{ git_email }}"
          register: git_set_email
          changed_when: git_set_email.rc == 0
  roles:
    - docker
    - spotify
    - codium
    - nvidia
    - steam
    - keys
    - minecraft
