---

- name: Provision system
  hosts: localhost
  gather_facts: true
  become: true
  become_user: "{{ su_user }}"
  any_errors_fatal: true
  debugger: 'on_failed'
  roles:
    - default_tasks
    - docker
    - codium
    - nvidia
    - discord
    - steam
    - minecraft
    - git
    - node
    - unity
    - spotify
    - keys
