---
- name: Provision system
  hosts: localhost
  gather_facts: true
  become: true
  become_user: root
  any_errors_fatal: true
  debugger: 'on_failed'

  pre_tasks:

    # Note: Ubuntu is not 'natively' supported - largely CI only.
    - name: Check if 'os_family' is supported
      ansible.builtin.assert:
        that:
          - "{{ ansible_facts.os_family in ('Debian', 'Ubuntu') }}"
        fail_msg: "Error! '{{ ansible_facts.os_family }}' is not supported!"
        success_msg: "'{{ ansible_facts.os_family }}' is supported."
      tags: ['always', 'os_family']

    # FIXME - consider this for managing users on init?
    # https://docs.ansible.com/ansible/latest/collections/ansible \
    # /builtin/user_module.html
    #
    - name: Check system_user exists
      ansible.builtin.command:
        cmd: id {{ system_user }}
      register: user_state
      changed_when: user_state.rc
      failed_when: user_state.rc != 0
      tags: ['always', 'user']
  roles:
    - docker
    - codium
    - nvidia
    - discord
    - steam
    - minecraft
    - git
    - node
    - unity
    - spotify
    - keys
