---

- name: Gather installed package lists.
  vars:
    apt_action_type: 'installed'
  ansible.builtin.include_role:
    name: apt


- name: Install Default Apt source packages where required
  ansible.builtin.apt:
    update_cache: true
    name:
      - "{{ item }}"
  with_items: "{{ apt.default_packages | difference(apt_installed_packages) }}"
