---

- name: Check for installed packages
  ansible.builtin.package_facts:
    manager:
      - apt
  register: packages


- name: Save package list to host variables
  ansible.builtin.set_fact:
    apt_installed_packages: "{{ ansible_facts['packages'].keys() }}"
