---

- name: Assert action_type is valid
  ansible.builtin.assert:
    that:
      - "apt_action_type in ('sources', 'packages')"
  tags:
    - always


- name: Provision debian apt sources.
  ansible.builtin.include_tasks:
    file: debian_sources.yaml
  when: apt_action_type == 'sources'
  tags:
    - always


- name: Install host default packages
  ansible.builtin.include_tasks:
    file: default_packages.yaml
  when: apt_action_type == 'packages'
  tags:
    - always
