---

- name: Gather installed package lists.
  vars:
    apt_action_type: 'installed'
  ansible.builtin.include_role:
    name: apt
  tags:
    - github


- name: Ensure i386 packages can be installed
  tags:
    - github
  ansible.builtin.include_role:
    name: dpkg


- name: Get list of required GitHub debs
  ansible.builtin.set_fact:
    github_required_debs: "{{ github.debs | map(attribute='name') }}"
  tags:
    - github


- name: Install debs from GitHub releases
  tags:
    - github
  vars:
    # FIXME: This is almost certainly a bad way of doing this.
    #
    gh_ns: "{{ github.debs | items2dict(key_name='name', value_name='namespace') }}"  # noqa: yaml[line-length]
    version: "{{ github.debs | items2dict(key_name='name', value_name='version') }}"  # noqa: yaml[line-length]
    file: "{{ github.debs | items2dict(key_name='name', value_name='file_name') }}"  # noqa: yaml[line-length]
  ansible.builtin.apt:
    deb: "https://github.com/{{ gh_ns[item] }}/releases/download/v{{ version[item] }}/{{ file[item] }}"  # noqa: yaml[line-length]
    state: present
  with_items: "{{ github_required_debs | difference(apt_installed_packages) }}"


# TODO: This does not verify whether packages actually need installing;
#       it just does it. I couldn't work out parsing `find` return to get the
#       present file paths properly.
#
# We rely on these types of applications being setup in /usr/local/bin
#
- name: Install binaries from GitHub releases
  tags:
    - github
  vars:
    # FIXME: This is almost certainly a bad way of doing this.
    #
    gh_ns: "{{ github.bins | items2dict(key_name='name', value_name='namespace') }}"  # noqa: yaml[line-length]
    version: "{{ github.bins | items2dict(key_name='name', value_name='version') }}"  # noqa: yaml[line-length]
    file: "{{ github.bins | items2dict(key_name='name', value_name='file_name') }}"  # noqa: yaml[line-length]
  ansible.builtin.get_url:
    url: "https://github.com/{{ gh_ns[item] }}/releases/download/v{{ version[item] }}/{{ file[item] }}"  # noqa: yaml[line-length]
    dest: "/usr/local/bin/{{ item }}"
    mode: "0755"
    group: "{{ su_group }}"
    owner: "{{ su_user }}"
  with_items: "{{ github.bins | map(attribute='name') }}"
