---

- name: Check for installed packages
  ansible.builtin.package_facts:
    manager:
      - apt
  register: packages
  tags:
    - nvidia

- name: Set up nvidia apt sources
  become: true
  become_user: "{{ su_user }}"
  vars:
    nvidia_packages:  # FIXME : There's some var duplication here.
      - nvidia-driver-libs:i386
      - linux-headers-amd64
      - nvidia-driver
  tags:
    - nvidia
  when: "nvidia_packages is not subset(ansible_facts['packages'].keys())"
  block:
    # This can vary between images and 'real' installs, so...
    #   a) Find wherever the debian sources file is
    #   b) Delete it
    #   c) Populate a managed one.
    #
    - name: Find debian source file
      debugger: 'always'
      ansible.builtin.find:
        paths:
          - /etc/apt/
        contains: "deb http://deb.debian.org/debian/"
        read_whole_file: true
      register: result
      # failed_when: "result.files | length == 0"




  # add apt source
  # - name: Replace apt sources.list for nVidia drivers
  #   ansible.builtin.template:
  #     src: templates/sources.j2
  #     dest: /etc/apt/sources.list
  #     owner: root
  #     group: root
  #     mode: "0644"
  #   tags: ['source', 'apt', 'nvidia', 'steam']

# FIXME : There's an undeclared dependency here on the apt
#         source being setup.
- name: Set up i386 nVidia drivers
  become: true
  become_user: "{{ su_user }}"
  vars:
    i386_packages:
      - nvidia-driver-libs:i386
  tags:
    - nvidia
  when: "i386_packages is not subset(ansible_facts['packages'].keys())"
  block:
    - name: Get current architectures
      ansible.builtin.command:
        cmd: dpkg --print-foreign-architectures
      changed_when: false  # idempotent
      register: arch

    - name: Add i386 as a valid architecture
      ansible.builtin.command:
        cmd: dpkg --add-architecture i386
      changed_when: "result._result.rc == 0"
      when: "'i386' not in arch.stdout_lines"

    - name: Install i386 packages
      ansible.builtin.apt:
        update_cache: true
        name:
          - "{{ item }}"
      with_items: "{{ i386_packages | difference(packages['ansible_facts']['packages'].keys()) }}"

# - name: Set up amd64 nVidia drivers
#   vars:
#     amd64_packages:
#       - linux-headers-amd64
#       - nvidia-driver
#   tags:
#     - nvidia

# - name: Install nVidia prerequisite drivers
#   become: true
#   ansible.builtin.apt:
#     clean: true
#     update_cache: true
#     install_recommends: false
#     name:
#       - linux-headers-amd64
#   tags: ['nvidia', 'apt', 'steam']


# - name: Install nVidia drivers
#   become: true
#   ansible.builtin.apt:
#     clean: true
#     update_cache: true
#     install_recommends: true  # Just install defaults - risky install.
#     name:
#       - nvidia-driver  # Would be nice to pin releases.
#   tags: ['nvidia', 'apt', 'steam']
