---

- name: Check for installed packages
  ansible.builtin.package_facts:
    manager:
      - apt
  register: packages
  tags:
    - nvidia


- name: Set up NVIDIA packages
  become: true
  become_user: "{{ su_user }}"
  vars:
    nvidia_packages:
      - nvidia-driver-libs:i386
      - linux-headers-amd64
      - nvidia-driver
  tags:
    - nvidia
  when: "nvidia_packages is not subset(ansible_facts['packages'].keys())"
  block:
    - name: Ensure managed apt sources are deployed
      ansible.builtin.include_role:
        name: apt

    - name: Ensure i386 packages can be installed
      ansible.builtin.include_role:
        name: dpkg

    # We don't refresh `ansible_facts['packages']` as subsequent jobs don't
    # depend on this state.
    - name: Install nvidia packages
      ansible.builtin.apt:
        update_cache: true
        name:
          - "{{ item }}"
      with_items: "{{ nvidia_packages | difference(packages['ansible_facts']['packages'].keys()) }}"
