---

- name: Gather installed package lists.
  vars:
    apt_action_type: 'installed'
  ansible.builtin.include_role:
    name: apt
  tags:
    - nvidia


- name: Set up NVIDIA packages
  become: true
  become_user: "{{ su_user }}"
  vars:
    nvidia_packages:
      - nvidia-driver-libs:i386
      - linux-headers-amd64
      - nvidia-driver
  tags:
    - nvidia
  when: "nvidia_packages is not subset(apt_installed_packages)"
  block:
    - name: Ensure managed apt sources are deployed
      vars:
        apt_action_type: 'sources'
      ansible.builtin.include_role:
        name: apt

    - name: Ensure i386 packages can be installed
      ansible.builtin.include_role:
        name: dpkg

    - name: Install nvidia packages
      ansible.builtin.apt:
        update_cache: true
        name:
          - "{{ item }}"
      with_items: "{{ nvidia_packages | difference(apt_installed_packages) }}"
