---
name: Ansible Tests
# yamllint disable-line rule:truthy
on: [push, pull_request]

jobs:
  tagcheck:
    runs-on: ubuntu-latest
    env:
      INPUT_USERNAME: www-data
    steps:
      - uses: actions/checkout@v4

      # FIXME - there must be a more native way to transport environment
      # variables between env.vars and the bash script environment.
      - name: Provision environment variables to scripts.
        run: >
          echo "INPUT_USERNAME=${INPUT_USERNAME}" >> .github-vars
          && echo "VIRTUAL_ENV=/home/${INPUT_USERNAME}/venvs/ansible"
          >> .github-vars
          && sudo chown 0600 .github-vars

      - name: Run bootstrap script.
        run: sudo ./bootstrap.sh

      - name: Source the venv and run Ansible
        run: sudo ./integration-tests/tag-regressions/test-tags.sh
