---
name: Static Tests
# yamllint disable-line rule:truthy
on: [pull_request]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master


  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v3


  ansiblelint:
    runs-on: ubuntu-latest
    container:
      image: python:3.11-bookworm
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: >
          apt update
          && apt install --assume-yes --no-install-recommends \
            sudo lsb-release

      - name: Mark as safe for git
        run: >
          git config --global \
            --add safe.directory /__w/provisioning/provisioning

      - name: Ansible-lint
        uses: ansible/ansible-lint@main
        with:
          setup_python: false
          requirements_file: ansible/requirements.yaml
