---
name: Static Tests
on: [push, pull_request]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master


  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: YAML Lint
        uses: ibiqlik/action-yamllint@v3


  ansiblelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ansible-lint
        uses: ansible/ansible-lint@main


  python-ruff:
    env:
      REQUIREMENTS: ansible/roles/discord/bin/updater/requirements.txt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Ruff.
        run: pip install -r ${REQUIREMENTS}

      - name: Check linting.
        run: ruff --verbose check .

      - name: Check formatting.
        run: ruff --verbose format .


  python-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Change workdir to Discord tooling.
        run: cd ${DISCORD_TOOL_PATH}

      - name: Install Pip requirements
        working-directory: ansible/roles/discord/bin/updater
        run: pip install -r requirements.txt

      - name: Run unittests
        working-directory: ansible/roles/discord/bin/updater
        run: python3 -m unittest
